title: Project
tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: true
              listable: true
              display: Title
              validate:
                - required
      -
        display: Hero
        fields:
          -
            handle: image
            field: common.image
          -
            handle: caption
            field:
              type: markdown
              localizable: true
              display: Caption
          -
            import: button
      -
        display: 'Page builder'
        fields:
          -
            import: page_builder
          -
            handle: iframe
            field:
              type: textarea
              display: iframe
  seo:
    display: SEO
    sections:
      -
        display: Basic
        instructions: 'Basic SEO settings.'
        fields:
          -
            import: 'statamic-peak-seo::seo_basic'
      -
        display: Advanced
        instructions: 'Advanced SEO settings.'
        fields:
          -
            import: 'statamic-peak-seo::seo_advanced'
      -
        display: 'Open Graph'
        instructions: 'Open Graph meta tags for social sharing.'
        fields:
          -
            import: 'statamic-peak-seo::seo_open_graph'
      -
        display: Sitemap
        instructions: 'Sitemap configuration.'
        fields:
          -
            import: 'statamic-peak-seo::seo_sitemap'
      -
        display: 'JSON-ld Schema'
        instructions: 'Custom JSON-ld schema objects.'
        fields:
          -
            import: 'statamic-peak-seo::seo_jsonld'
  sidebar:
    display: Sidebar
    sections:
      -
        display: Meta
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - required
              display: Slug
          -
            handle: work
            field:
              type: entries
              collections:
                - pages
              max_items: 3
              listable: false
              localizable: true
              display: 'Associated workflows'
